### ISSUE TITLE
Remove `invalid` class if input field is valid

### ISSUE THREAD

**Issue by sajibcse68** [cowrypay/lobby#51]
Say, `First Name` and `Last Name` were invalid first time, so `click` event listener added `invalid` class into that fields. But second time if the fields are valid then `invalid` class are not removing.

<img width="505" alt="payment-method-form" src="https://cloud.githubusercontent.com/assets/8726459/26095763/9dd2ab94-3a40-11e7-8324-c5b8d0217044.png">

**Comment by sajibcse68** [comment]
https://github.com/cowrypay/lobby/blob/master/js/views/lobby/payment-method-new.js#L163

Add a else like
```
} else {
$(`#second-form input[name=${it.name}]`).removeClass('invalid');
}
```

**Comment by sajibcse68** [comment]
@a8uhnf How about also create a common `backbone change events` on these Four fields to add/remove `invalid` class?

**Comment by a8uhnf** [comment]
okay I'm adding this
